[[questions]]
question = "Under what specific network topology conditions does the global clustering coefficient fail to accurately represent the local clustering behavior of typical nodes?"
answer = "When the network is degree heterogeneous. This is because a single hub can create substantially many triangles in the network, not representing the number of triangles typical nodes in the network form."

[[questions]]
question = "What are the two defining quantitative characteristics that distinguish small-world networks from both regular lattices and random networks?"
answer = "Small-world networks are characterized by having both a high clustering coefficient (like regular lattices) and a short average path length (like random networks)."
