name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      run: |
        # Install uv
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        uv venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Quiz Challenge
      id: quiz-challenge
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Quiz Challenge
        setup-command: echo "Environment already set up"
        command: |
          if [ -z "${{ secrets.OPENROUTER_API_KEY }}" ]; then
            echo "OPENROUTER_API_KEY secret not found"
            exit 1
          fi
          uv run python -m llm_quiz.cli \
            --config config.toml \
            --quiz-file quiz.toml \
            --api-key ${{ secrets.OPENROUTER_API_KEY }} \
            --output quiz_results.json
        timeout: 10
        max-score: 10

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        QUIZ-CHALLENGE_RESULTS: "${{steps.quiz-challenge.outputs.result}}"
      with:
        runners: quiz-challenge